### ISSUE TITLE
Fragment values (following a "#") are not allowed in this URL.

### ISSUE THREAD

**Issue by fraserxu** [googlearchive/realtime-tasks#4]
I'm new to Google Drive SDK. And when setting the OPEN Url, I pasted `http://localhost/#/todos/{ids}/?user={userId}` in it, and it tells me `Fragment values (following a "#") are not allowed in this URL`. How should I set the correct OPEN Url?

Can u give me an right example? thx!

**Comment by sqrrrl** [comment]
I don't see that error, but localhost isn't currently allowed and you need to change localhost to an actual hostname. If that still doesn't work, please include a screenshot

**Comment by fraserxu** [comment]
I've changed that to my own domain which is `xvfeng.me`, and it still tells me that:
![Google APIs Console](https://f.cloud.github.com/assets/1183541/347389/1a0218d8-9eca-11e2-8e53-c8709d1a876d.png)
Seems that `#` and `?` is not allowed here. How can I set that? 
And thx for your reply! @sqrrrl

**Comment by sqrrrl** [comment]
This error happens if you also enable the "Automatically initiate the OAuth 2.0 flow when users open my application from Drive" option. That approach is discouraged and should remain unchecked.

As for why the two are incompatible...technically they're not an we could relax that restriction. But best not to check that option in the first place.
